### ISSUE TITLE
Does this duplicate m4?

### ISSUE THREAD

**Issue by bs27975** [iwonbigbro/bashpp#19]
Having googled 'bash preprocessor', I have come here to [Bash Pre-Processor](https://github.com/iwonbigbro/bashpp)

In developing bash scripts, I have found it handy to run 'bash -n' on them beforehand, as well as [shellcheck](https://github.com/koalaman/shellcheck#shellcheck).  In my ponderings, I am also (re-)minded of make.

In considering (googling) the idea of a bash preprocessor, I have also come across 'm4'.

Are there dis/advantages to using bashpp instead of m4, and acclimating it instead of the other?

**Comment by iwonbigbro** [comment]
bashpp is a bash preprocessor written entirely in bash.  The only prerequisite on any build machine is that you have bash installed.  m4 is a generic macro processor.  You can use that and you can even use cpp to preprocess bash scripts.  The problem is, you need to have either of those installed in your build environment.  If you don't have them and you operate in a build environment that is strictly controlled, you're going to run into problems.
